<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['guide']=array (
  'id' => '1',
  'name' => 'guide',
  'description' => '说明书',
  'perpage' => '15',
  'hasattach' => '1',
  'built_in' => '0',
  'fields' => 
  array (
    1 => 
    array (
      'id' => '1',
      'name' => 'classid',
      'description' => '所属分类',
      'model' => '1',
      'type' => 'select_from_model',
      'length' => '2',
      'values' => 'guide|name',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    2 => 
    array (
      'id' => '2',
      'name' => 'title',
      'description' => '标题',
      'model' => '1',
      'type' => 'input',
      'length' => '200',
      'values' => '',
      'width' => '300',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    9 => 
    array (
      'id' => '9',
      'name' => 'alias',
      'description' => 'URL别名',
      'model' => '1',
      'type' => 'input',
      'length' => '200',
      'values' => '',
      'width' => '300',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '2',
      'editable' => '1',
    ),
    4 => 
    array (
      'id' => '4',
      'name' => 'type',
      'description' => '打开类型',
      'model' => '1',
      'type' => 'select',
      'length' => '1',
      'values' => 
      array (
        1 => '正常',
        2 => '外链',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    3 => 
    array (
      'id' => '3',
      'name' => 'content',
      'description' => '内容',
      'model' => '1',
      'type' => 'wysiwyg',
      'length' => '0',
      'values' => '',
      'width' => '600',
      'height' => '300',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '4',
      'editable' => '1',
    ),
    5 => 
    array (
      'id' => '5',
      'name' => 'url',
      'description' => '外链URL',
      'model' => '1',
      'type' => 'input',
      'length' => '200',
      'values' => '',
      'width' => '300',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '5',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '1',
    1 => '2',
    2 => '4',
  ),
  'searchable' => 
  array (
    0 => '1',
    1 => '2',
  ),
);