<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['current_role']=array (
  'id' => '2',
  'name' => '管理员',
  'rights' => 
  array (
    0 => 'system@password',
    1 => 'system@cache',
    2 => 'setting@site',
    3 => 'setting@backend',
    4 => 'plugin@view',
    5 => 'plugin@add',
    6 => 'plugin@edit',
    7 => 'plugin@del',
    8 => 'plugin@export',
    9 => 'plugin@import',
    10 => 'plugin@active',
    11 => 'plugin@deactive',
    12 => 'module@run',
    13 => 'model@view',
    14 => 'model@add',
    15 => 'model@edit',
    16 => 'model@del',
    17 => 'model@fields',
    18 => 'model@add_filed',
    19 => 'model@edit_field',
    20 => 'model@del_field',
    21 => 'category@view',
    22 => 'category@add',
    23 => 'category@edit',
    24 => 'category@del',
    25 => 'category@fields',
    26 => 'category@add_filed',
    27 => 'category@edit_field',
    28 => 'category@del_field',
    29 => 'content@view',
    30 => 'content@form@add',
    31 => 'content@form@edit',
    32 => 'content@save@add',
    33 => 'content@save@edit',
    34 => 'content@del',
    35 => 'category_content@view',
    36 => 'category_content@form@add',
    37 => 'category_content@form@edit',
    38 => 'category_content@save@add',
    39 => 'category_content@save@edit',
    40 => 'category_content@del',
    41 => 'role@view',
    42 => 'role@add',
    43 => 'role@edit',
    44 => 'role@del',
    45 => 'user@view',
    46 => 'user@add',
    47 => 'user@edit',
    48 => 'user@del',
    49 => 'taobao/setting@api',
    50 => 'taobao/setting@category',
    51 => 'taobao/setting@basic',
    52 => 'taobao/setting@view',
    53 => 'taobao/country@express',
    54 => 'taobao/member@view',
    55 => 'taobao/member@add',
    56 => 'taobao/order@view',
    57 => 'taobao/delivery@view',
    58 => 'taobao/inviter@view',
    59 => 'taobao/setting@email',
    60 => 'taobao/inviter@cash',
  ),
  'models' => 
  array (
    0 => 'guide',
    1 => 'company',
    2 => 'slider',
    3 => 'news',
    4 => 'articles',
  ),
  'category_models' => 
  array (
    0 => 'guide',
  ),
  'plugins' => 
  array (
    0 => '0',
  ),
);